version: '3.7'
services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  msfarm:
    build:
      dockerfile: ./dockerfile
      context: .
    image: spacemonkeys/msfarm
    container_name: msfarm
    ports: 
      - "8320:8320"
    depends_on: 
      - mongodb 
volumes:
  mongodb_data_container: